# 예시입니다..
FROM mysql:5.7

# ENV MYSQL_USER mysql_user
# ENV MYSQL_PASSWORD mysql_password
# ENV MYSQL_ROOT_PASSWORD mysql_root_password
# ENV MYSQL_DATABASE visitlog

# COPY /Database/ /docker-entrypoint-initdb.d/

# 이미지 빌드 명령어
# docker build -t 이미지명

#실행
# docker run --name 컨테이너 -p 3306:3306


WORKDIR /Database