# 여기는 현재 그냥 테스트용으로 나둡니다..
FROM python:3.8.17

# CMD ["/bin/sh"]

WORKDIR /Back-End

# COPY requirements.txt requirements.txt

# RUN pip install -r requirements.txt

# EXPOSE 8889

# ENTRYPOINT [ "jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--no-browser" ]