# FROM tensorflow/tensorflow:latest-gpu
FROM python:3.8.5

WORKDIR /Back-End

# COPY requirements.txt requirements.txt

# RUN pip install -r requirements.txt

# EXPOSE 8888

# ENTRYPOINT [ "jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--no-browser" ]